const PatientsActionsTypes = {
  GET_ALL_PATIENTS_START: "GET_ALL_PATIENTS_START",
  GET_ALL_PATIENTS_SUCCESS: "GET_ALL_PATIENTS_SUCCESS",
  GET_ALL_PATIENTS_FAILURE: "GET_ALL_PATIENTS_FAILURE",
  GET_A_PATIENT_START: "GET_A_PATIENT_START",
  GET_A_PATIENT_SUCCESS: "GET_A_PATIENT_SUCCESS",
  GET_A_PATIENT_FAILURE: "GET_A_PATIENT_FAILURE",
  POST_A_PATIENT_START: "POST_A_PATIENT_START",
  POST_A_PATIENT_SUCCESS: "POST_A_PATIENT_SUCCESS",
  POST_A_PATIENT_FAILURE: "POST_A_PATIENT_FAILURE",
  DELETE_A_PATIENT_START: "DELETE_A_PATIENT_START",
  DELETE_A_PATIENT_SUCCESS: "DELETE_A_PATIENT_SUCCESS",
  DELETE_A_PATIENT_FAILURE: "DELETE_A_PATIENT_FAILURE",
  PATCH_A_PATIENT_START: "PATCH_A_PATIENT_START",
  PATCH_A_PATIENT_SUCCESS: "PATCH_A_PATIENT_SUCCESS",
  PATCH_A_PATIENT_FAILURE: "PATCH_A_PATIENT_FAILURE",
};

export default PatientsActionsTypes;
